// Serialized bindings and production input/submit handlers; no live room requests.
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict');
const root=path.resolve(__dirname,'../..');
const ts=require('/Users/yy/.nvm/versions/node/v22.19.0/lib/node_modules/nexe/node_modules/typescript/lib/typescript.js');
class Component {} class Slider {} class ProgressBar {} class Label {} class Button {}
const cc={Component,Slider,ProgressBar,Label,Button,_decorator:{ccclass:c=>c,property:()=>()=>{}}};
let Buyin,commands=[];
const account={guuid:'sample-user',gold:'5000',roomSetting:'底皮 1/3 最小带入500',reqRoomCommand:s=>commands.push(JSON.parse(s))};
function load(file){const m={exports:{}};const r=ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2017,experimentalDecorators:true},reportDiagnostics:true});assert.equal(r.diagnostics.length,0);vm.runInNewContext(r.outputText,{cc,module:m,exports:m.exports,console,require(n){const key=n.split('/').pop();if(key==='BuyinDisplay')return {default:Buyin};if(key==='GameDataManager')return {default:{getAccount:()=>account}};if(key==='Tool')return {default:{GetChild:(n,p)=>n.find(p)}};if(n==='kbengine')return {};return {default:Component}}});return m.exports.default;}
Buyin=load('assets/scripts/common/BuyinDisplay.ts');
const Controller=load('assets/scripts/UI/panelGameView.ts');
let count=0;function test(name,f){f();count++;console.log('PASS',name);}
function fixture(){const b=new Buyin();let listeners=[];b.slider={progress:0,enabled:true,node:{on:(e,fn,ctx)=>listeners.push({e,fn,ctx}),off:(e,fn,ctx)=>listeners=listeners.filter(x=>x.e!==e||x.fn!==fn||x.ctx!==ctx)}};b.fill={progress:0};for(const k of ['amount','minimum','maximum','already','balance'])b[k]={string:''};b.confirm={interactable:true};b.onLoad();b.drag=p=>{b.slider.progress=p;listeners.filter(x=>x.e==='slide').forEach(x=>x.fn.call(x.ctx))};b.listeners=()=>listeners.length;return b;}
test('server values replace sample data and preserve integer step range',()=>{const b=fixture();b.configure(500,5200,1200);assert.equal(b.maximum.string,'5,000');assert.equal(b.already.string,'1,200');assert.equal(b.balance.string,'5,200');assert.equal(b.currentAmount,500);b.drag(1/3);assert.equal(b.currentAmount,2000);assert.equal(b.amount.string,'2,000');assert.equal(b.fill.progress,b.slider.progress);b.drag(1);assert.equal(b.currentAmount,5000);});
test('one available amount stays finite and cannot move',()=>{const b=fixture();b.configure(500,500,0);b.drag(1);assert.equal(b.currentAmount,500);assert.equal(b.slider.progress,0);assert.equal(b.slider.enabled,false);assert.equal(b.confirm.interactable,true);});
test('zero/insufficient/invalid ranges cannot confirm or produce NaN',()=>{for(const [min,balance] of [[500,499],[500,0],[0,500],[NaN,500],[500,Infinity],[-1,500]]){const b=fixture();b.configure(min,balance,0);b.drag(1);assert.equal(b.currentAmount,0);assert.equal(b.fill.progress,0);assert.equal(b.confirm.interactable,false);}});
test('fractional steps do not drift beyond balance',()=>{const b=fixture();b.configure(.1,.3,0);b.drag(1);assert.equal(b.currentAmount,.3);assert.equal(b.maximum.string,'0.3');for(let i=0;i<=10;i++){b.drag(i/10);assert(b.currentAmount<=.3);assert(Number.isFinite(b.slider.progress));}});
test('reopening resets selection and never accumulates slider callbacks',()=>{const b=fixture();for(let i=0;i<20;i++){b.configure(500,5000,0);assert.equal(b.currentAmount,500);b.drag(1);}assert.equal(b.listeners(),1);b.configure(200,1200,100);assert.equal(b.currentAmount,200);assert.equal(b.maximum.string,'1,200');b.onDestroy();assert.equal(b.listeners(),0);});
const b=fixture();b.configure(500,5000,0);b.drag(1/3);
const modal={active:true,getComponent:t=>t===Buyin?b:null};
const c=new Controller();c.node={getChildByName:()=>({active:true}),find:p=>{assert.equal(p,'带入窗口');return modal}};c.gameLogic={GetPlayerCtlByID:()=>({info:{strUserID:'sample-user',req_club_id:'sample-club'}})};c.CheckCanSitByGps=()=>true;c.preSitState='selecting';c.ShowMsg=s=>c.lastMessage=s;
test('confirmed request uses numeric amount and retains pre-sit/club protocol',()=>{c.onButtonClick({node:{name:'确认带入',parent:modal}});assert.equal(commands.length,1);assert.equal(commands[0].money,2000);assert.equal(commands[0].type,'直接');assert.equal(commands[0].club_id,'sample-club');assert.equal(c.preSitState,'submitting');assert.equal(modal.active,false);});
test('ordinary top-up remains application type and invalid amount is blocked',()=>{c.preSitState='idle';b.drag(1);c.onButtonClick({node:{name:'确认带入',parent:modal}});assert.equal(commands[1].type,'申请');b.configure(500,0,0);c.onButtonClick({node:{name:'确认带入',parent:modal}});assert.equal(commands.length,2);assert(c.lastMessage.includes('大于0'));});
test('cancel and close preserve reservation cleanup',()=>{let cancelled=0;c.CancelPreSitReservation=()=>cancelled++;const m={name:'带入窗口',active:true};c.onButtonClick({node:{name:'关闭上层',parent:m}});assert.equal(m.active,false);m.active=true;c.onButtonClick({node:{name:'关闭上上层',parent:{parent:m}}});assert.equal(m.active,false);assert.equal(cancelled,2);});
test('prefab and scene bind every live component and keep unrelated baseline objects',()=>{for(const [file,before] of [['assets/resources/UI/panelGameView.prefab','panelGameView.prefab'],['assets/Scenes/drh8.fire','drh8.fire']]){const a=JSON.parse(fs.readFileSync(path.join(root,file)));const old=JSON.parse(fs.readFileSync(path.join(root,'art_sources/v8-repairs/buyin/before',before)));const ri=old.findIndex(o=>o.__type__==='cc.Node'&&o._name==='带入窗口');const scope=new Set();function collect(i){scope.add(i);const n=old[i];n._components.forEach(r=>scope.add(r.__id__));n._children.forEach(r=>collect(r.__id__));}collect(ri);old.forEach((o,i)=>{if(!scope.has(i))assert.deepEqual(a[i],o,`${file}: unrelated object ${i}`)});const d=a.find(o=>o.__type__==='be1bamoGq5K5b9xC3bkm10h');assert(d);for(const k of ['slider','fill','amount','minimum','maximum','already','balance','confirm'])assert(a[d[k].__id__]);assert.equal(a[d.slider.__id__].__type__,'cc.Slider');assert.equal(a[d.amount.__id__]._enableWrapText,false);}});
console.log(count+' buy-in regressions passed.');
