// Production real-time record handlers with simulated server/resource callbacks.
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict');
const root=path.resolve(__dirname,'../..');
const ts=require('/Users/yy/.nvm/versions/node/v22.19.0/lib/node_modules/nexe/node_modules/typescript/lib/typescript.js');
class Component {} class Label {} class ScrollView {} class Layout {}
const cc={Component,Label,ScrollView,Layout,Color:{},color:(r,g,b,a=255)=>({r,g,b,a}),isValid:n=>!!n&&!n.destroyed,
    _decorator:{ccclass:c=>c,property:()=>()=>{}},error:()=>{},Node:{EventType:{TOUCH_START:'touchstart'}}};
let account,pending=[];
const src=fs.readFileSync(path.join(root,'assets/scripts/UI/panelGameView.ts'),'utf8');
const result=ts.transpileModule(src,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2017,experimentalDecorators:true},reportDiagnostics:true});
assert.equal(result.diagnostics.length,0);
const moduleOut={exports:{}};
vm.runInNewContext(result.outputText,{cc,console,module:moduleOut,exports:moduleOut.exports,require(n){
    const key=n.split('/').pop();
    if(key==='GameDataManager')return {default:{getAccount:()=>account}};
    if(key==='Tool')return {default:{GetChild:(n,p)=>n.find(p)}};
    if(key==='WebLoadingManager')return {default:{loadBlockingRes:(p,s,cb)=>pending.push(cb)}};
    if(key==='Debug')return {default:{Error:()=>{}}};
    if(n==='kbengine')return {};return {default:Component};
}});
const Controller=moduleOut.exports.default;
function node(name){return {name,active:true,color:{r:250,g:240,b:214,a:255},label:{string:''},children:[],getComponent(t){return t===Label?this.label:t===Layout?{updateLayout:()=>this.layoutUpdates=(this.layoutUpdates||0)+1}:{scrollToTop:()=>this.scrolled=true};},getChildByName(name){return this.children.find(n=>n.name===name);},removeAllChildren(){this.children=[];},getComponentsInChildren(){return this.children.filter(n=>['name','in','score','V8离桌'].includes(n.name)).map(n=>({node:n}));}};}
cc.instantiate=()=>{const n=node('带入记录');n.children=['name','in','score','V8本人','V8本人底','V8隔行','V8离桌'].map(node);Object.defineProperty(n,'parent',{set(p){p.children.push(this);}});return n;};
let c,nodes,content;
function fixture(){pending=[];account={guuid:'self',roomID:1,roomSetting:'1/3',reqAccountCommand:()=>{},setDefinedProperty:(k,v)=>account[k]=v};c=new Controller();nodes={};['实时战绩','实时战绩/bg','实时战绩/战绩列表','实时战绩/战绩列表/view/content','实时战绩/V8列表状态','实时战绩/奖池','实时战绩/总带入','实时战绩/总得分','实时战绩/搓牌开关/V8状态'].forEach(p=>nodes[p]=node(p));c.node={find:p=>{assert(nodes[p],p);return nodes[p];}};c.gameLogic={arrayPlayer:[{info:{strUserID:'self'}},{info:{strUserID:'other'}}]};content=nodes['实时战绩/战绩列表/view/content'];return c;}
const record=(id,score=0,init=2000)=>({id,name:id,init_money:init,total_score:score});
function receive(rows,pool='128.60'){c.onGamePlayerListInfo(JSON.stringify({GamePlayerListInfo:rows,reward_pool:pool}));}
function flush(){const cb=pending.shift();assert(cb);cb(null,{});}
let count=0;function test(name,fn){fixture();fn();count++;console.log('PASS',name);}
test('request preserves protocol and resets the real scroll/list state',()=>{let request;account.reqAccountCommand=(a,b)=>request=[JSON.parse(a),b];content.children=[node('old')];c.GetReadRecordInfo();assert.equal(content.children.length,0);assert(nodes['实时战绩/战绩列表'].scrolled);assert.equal(nodes['实时战绩/V8列表状态'].label.string,'正在加载…');assert.equal(request[0].header,'获取_游戏内玩家_信息_命令');});
test('many rows use one prefab load and preserve server order',()=>{receive(Array.from({length:40},(_,i)=>record('user-'+i,i)));assert.equal(pending.length,1);flush();assert.equal(content.children.length,40);assert.equal(content.children[39].getChildByName('name').label.string,'user-39');assert.equal(content.layoutUpdates,1);});
test('self, alternating, signed and departed states stay data driven',()=>{receive([record('self',1280),record('other',-680),record('gone',0)]);flush();assert(content.children[0].getChildByName('V8本人底').active);assert(content.children[1].getChildByName('V8隔行').active);assert(!content.children[1].getChildByName('V8本人').active);assert.equal(content.children[0].getChildByName('score').label.string,'+1,280');assert.equal(content.children[1].getChildByName('score').label.string,'-680');assert(content.children[2].getChildByName('V8离桌').active);assert.deepEqual(content.children[2].getChildByName('score').color,{r:133,g:158,b:179,a:255});});
test('totals retain positive-score-only semantics and server units',()=>{receive([record('self',1280,2000),record('other',-680,1500),record('gone',560,500)]);assert.equal(nodes['实时战绩/总带入'].label.string,'4,000');assert.equal(nodes['实时战绩/总得分'].label.string,'1,840');assert.equal(nodes['实时战绩/奖池'].label.string,'128.60');});
test('small-stake row conversion still divides by ten exactly once',()=>{account.roomSetting='0.1/0.3';receive([record('self',128,200)]);flush();assert.equal(content.children[0].getChildByName('in').label.string,'20');assert.equal(content.children[0].getChildByName('score').label.string,'+12.8');assert.equal(nodes['实时战绩/总带入'].label.string,'200');});
test('empty replaces old rows and clears stale totals without asset work',()=>{receive([record('self')]);flush();receive([],'0');assert.equal(content.children.length,0);assert.equal(pending.length,0);assert.equal(nodes['实时战绩/总带入'].label.string,'0');assert.equal(nodes['实时战绩/V8列表状态'].label.string,'暂无战绩');});
test('older resource callback cannot append into a newer response',()=>{receive([record('old')]);receive([record('new')]);flush();assert.equal(content.children.length,0);flush();assert.equal(content.children.length,1);assert.equal(content.children[0].getChildByName('name').label.string,'new');});
test('reopening invalidates in-flight resource callback',()=>{receive([record('old')]);c.GetReadRecordInfo();flush();assert.equal(content.children.length,0);});
test('closed, destroyed, changed-account and changed-room callbacks are ignored',()=>{for(const mode of ['closed','destroyed','account','room']){fixture();receive([record('self')]);if(mode==='closed')nodes['实时战绩'].active=false;if(mode==='destroyed')content.destroyed=true;if(mode==='account')account={...account};if(mode==='room')account.roomID=2;flush();assert.equal(content.children.length,0,mode);}});
test('failed resource load exposes recovery state',()=>{receive([record('self')]);pending.shift()(new Error('test'));assert(nodes['实时战绩/V8列表状态'].active);assert.equal(nodes['实时战绩/V8列表状态'].label.string,'加载失败，请重新打开');});
test('malformed and closed-panel replies cannot replace the visible list',()=>{content.children=[node('old')];c.onGamePlayerListInfo('{bad');c.onGamePlayerListInfo('{}');assert.equal(content.children.length,1);nodes['实时战绩'].active=false;receive([record('new')]);assert.equal(pending.length,0);});
test('inside touches and list drags keep drawer open; outside touch closes',()=>{const bg=nodes['实时战绩/bg'];bg.width=594;bg.height=1334;bg.convertToNodeSpaceAR=p=>p;let closed=0;c.CloseAllShow=()=>closed++;for(const p of [{x:0,y:0},{x:296,y:600},{x:-297,y:-650}])c.OnRealtimeRecordTouch({getLocation:()=>p});assert.equal(closed,0);c.OnRealtimeRecordTouch({getLocation:()=>({x:300,y:0})});assert.equal(closed,1);});
test('squeeze label matches the setting toggle',()=>{c.onToggleClick({node:{name:'搓牌开关'},isChecked:true});assert.equal(account.player_setting,'True');assert.equal(nodes['实时战绩/搓牌开关/V8状态'].label.string,'已开启');c.onToggleClick({node:{name:'搓牌开关'},isChecked:false});assert.equal(nodes['实时战绩/搓牌开关/V8状态'].label.string,'已关闭');});
function read(p){return JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));}
test('latest application preserves all unrelated prefab and scene objects',()=>{for(const [file,name] of [['assets/resources/UI/panelGameView.prefab','panelGameView.prefab'],['assets/Scenes/drh8.fire','drh8.fire']]){const a=read(file),old=read('art_sources/v8-repairs/realtime-record/last-apply-before/'+name);const scope=new Set();function visit(i){scope.add(i);const n=old[i];n._components.forEach(r=>scope.add(r.__id__));n._children.forEach(r=>visit(r.__id__));}visit(old.findIndex(n=>n.__type__==='cc.Node'&&n._name==='实时战绩'));old.forEach((n,i)=>{if(!scope.has(i))assert.deepEqual(a[i],n,file+' unrelated '+i);});}});
test('both scroll views have independent content/masks and native scrollbar bindings',()=>{const a=read('assets/resources/UI/panelGameView.prefab');const views=['战绩列表','围观列表'].map(name=>a.find(n=>n.__type__==='cc.Node'&&n._name===name));const comps=views.map(n=>n._components.map(r=>a[r.__id__]).find(c=>c.__type__==='0d83fc3wRhLQ5psw1ZE2ymI'));assert.notEqual(comps[0].content.__id__,comps[1].content.__id__);comps.forEach(c=>{assert(c.vertical);assert.equal(c.horizontal,false);assert.equal(a[c.verticalScrollBar.__id__].__type__,'cc.Scrollbar');});const watch=a[comps[1].content.__id__];const layout=watch._components.map(r=>a[r.__id__]).find(c=>c.__type__==='cc.Layout');assert.equal(layout._resize,1);assert.equal(layout['_N$layoutType'],3);assert.equal(layout['_N$cellSize'].width,138);});
test('compact textures are packable and avoid full-screen image duplication',()=>{const cuts=read('art_sources/v8-repairs/realtime-record/cuts.json');assert(Object.values(cuts).reduce((s,c)=>s+c.bytes,0)<200*1024);assert(Object.values(cuts).reduce((s,c)=>s+c.rgba_bytes,0)<512*1024);for(const [k,c] of Object.entries(cuts)){const m=read('assets/resources/V7/realtime_v8_'+k+'.png.meta');assert(m.packable);assert(Math.max(...c.size)<=300);if(k==='panel'||k==='drawer')assert(c.border>0);}});
test('scroll content Widgets cannot snap each drag back to the top',()=>{const a=read('assets/resources/UI/panelGameView.prefab');for(const n of a.filter(n=>n.__type__==='cc.Node'&&n._name==='content')){const parent=n._parent&&a[n._parent.__id__];const grand=parent&&parent._parent&&a[parent._parent.__id__];if(!grand||!['战绩列表','围观列表'].includes(grand._name))continue;const widget=n._components.map(r=>a[r.__id__]).find(c=>c.__type__==='cc.Widget');assert.notEqual(widget.alignMode,2);}});
console.log(count+' real-time record regressions passed.');
